{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "LA 1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "LA 5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "LA 15",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ( avg by (instance) (irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Freee Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  }
 ]
}